### ISSUE TITLE
apply HTML5 best practice in nav

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/theDavidBarton.github.io#128]
something like these:
```html
<nav>
  <ul>
    <li><a>Item 1</a></li>
    <li><a>Item 2</a></li>
    <li><a>Item 3</a></li>
  </ul>
</nav>
```
```css
nav > ul > li {
  display: inline;
  list-style-type: none;
  padding-right: 1rem;
  float: left;
}
```
