### ISSUE TITLE
enhance <code> texts

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/theDavidBarton.github.io#161]
at the moment is not very visible.

```css
code {
  ...
  color: #e00000; /* bit darker red */
  ...
  background-color: #f1f3f4;
  padding: 0.15rem;
}
```
