### ISSUE TITLE
make desktop Prism window wider

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/theDavidBarton.github.io#173]
for desktop this would be a nice width:

```css
pre[class*="language-"] {
    padding: 1em;
    margin: 3em -8em;
    overflow: auto;
}
```

mobile can remain the same as now.

![image](https://user-images.githubusercontent.com/43063460/177057446-3573f4b4-4f44-48c3-b8d6-f630376da906.png)
