### ISSUE TITLE
finetune list alignment

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/theDavidBarton.github.io#68]
```css
.cv-border-style {
    margin: 25px 25px 25px 0px;
    padding-left: 30px;
    border-width: thick;
    border-radius: 5px 5px 135px 5px;
    border-left: 25px solid #9fe0c6;
}
```
before (desktop):

![image](https://user-images.githubusercontent.com/43063460/91644020-95c4eb00-ea38-11ea-9e40-9874f71cda88.png)

after (desktop):

![image](https://user-images.githubusercontent.com/43063460/91644011-7fb72a80-ea38-11ea-88cd-07edf62ad4d4.png)

before (mobile):

![image](https://user-images.githubusercontent.com/43063460/91644124-6bbff880-ea39-11ea-8277-c55fd533902c.png)

after (mobile):

![image](https://user-images.githubusercontent.com/43063460/91644050-cb69d400-ea38-11ea-84d7-97090972e217.png)
